theme: jekyll-theme-modernist
paginate: 10
gems: [jekyll-paginate]
title: Perpetual Thrill
author: ""
description: Creators of As One, an interactive, biofeedback driven flame effect
goodrepo: "https://github.com/perpetualthrill/as-one"

