theme: jekyll-theme-modernist
paginate: 10
gems: [jekyll-paginate]
title: Perpetual Thrill
description: Home of As One, an interactive, biofeedback driven flame effect
github_repo: as-one
github_username: perpetualthrill
