theme: jekyll-theme-modernist
paginate: 10

gems:
  - jekyll-paginate
  - jekyll-feed

title: Perpetual Thrill
author: ""
description: "Creators of <a href='/about/'>As One</a>, an interactive, biofeedback driven flame effect"
goodrepo: "https://github.com/perpetualthrill/as-one"

